#!/usr/bin/env bash
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

# ========= CONFIG =========
SUPABASE_ROOT="${SUPABASE_ROOT:-$HOME/supabase-local}"
NODE_MAJOR_REQUIRED=20

# Determine repository root (where this script's parent directory is)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Use the repo's existing supabase/ folder instead of creating a fresh project
# This allows us to use the existing 364+ migrations
PROJECT_DIR="${REPO_ROOT}"

# ========= HELPERS =========
log()  { printf "\n[+] %s\n" "$*"; }
warn() { printf "\n[!] %s\n" "$*" >&2; }
die()  { printf "\n[x] %s\n" "$*" >&2; exit 1; }

# Sudo wrapper for unattended mode
# Set SUDO_PASS environment variable for unattended execution
do_sudo() {
  if [ -n "${SUDO_PASS:-}" ]; then
    echo "$SUDO_PASS" | sudo -S "$@" 2>/dev/null
  else
    sudo "$@"
  fi
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

is_wsl() {
  grep -qi microsoft /proc/version 2>/dev/null
}

node_major() {
  if command -v node >/dev/null 2>&1; then
    node -v | sed 's/^v//' | cut -d. -f1
  else
    echo "0"
  fi
}

docker_works() {
  docker info >/dev/null 2>&1
}

start_docker_best_effort() {
  # Prefer systemd if available
  if command -v systemctl >/dev/null 2>&1 && ps -p 1 -o comm= 2>/dev/null | grep -q systemd; then
    log "Starting Docker with systemd..."
    do_sudo systemctl enable --now docker >/dev/null 2>&1 || true
  elif command -v service >/dev/null 2>&1; then
    log "Starting Docker with service..."
    do_sudo service docker start >/dev/null 2>&1 || true
  fi

  # If still not running, attempt manual dockerd (useful on some WSL setups)
  if ! docker_works; then
    log "Docker daemon not reachable yet. Attempting manual dockerd start..."
    do_sudo nohup dockerd >/tmp/dockerd.log 2>&1 & disown || true
    sleep 5
  fi
}

ensure_docker_access_for_current_user() {
  # Ensure docker group exists and user is added
  do_sudo groupadd -f docker >/dev/null 2>&1 || true
  do_sudo usermod -aG docker "$USER" >/dev/null 2>&1 || true

  # Grant immediate access via ACL to avoid logout/login requirement (WSL-friendly)
  if command -v setfacl >/dev/null 2>&1 && [ -S /var/run/docker.sock ]; then
    do_sudo setfacl -m "user:${USER}:rw" /var/run/docker.sock >/dev/null 2>&1 || true
  fi
}

check_ports_free() {
  # Supabase local defaults: API 54321, DB 54322, Studio 54323
  local ports=(54321 54322 54323)
  for p in "${ports[@]}"; do
    if ss -lnt 2>/dev/null | awk '{print $4}' | grep -qE ":${p}$"; then
      die "Port ${p} is already in use. Stop the service using it and re-run."
    fi
  done
}

install_docker_gpg_key() {
  # Download GPG key to temp file first (avoids pipe issues with sudo)
  local tmp_key="/tmp/docker-gpg-key.$$"
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o "$tmp_key"
  gpg --dearmor -o "${tmp_key}.bin" < "$tmp_key" 2>/dev/null
  do_sudo cp "${tmp_key}.bin" /etc/apt/keyrings/docker.gpg
  do_sudo chmod a+r /etc/apt/keyrings/docker.gpg
  rm -f "$tmp_key" "${tmp_key}.bin"
}

# Generate .env.local with local Supabase credentials
generate_env_local() {
  log "Capturing local Supabase credentials..."

  local status_json="/tmp/supabase-status-$$.json"

  # Get status in JSON format
  if ! npx --yes supabase status --output json > "$status_json" 2>/dev/null; then
    warn "Could not get supabase status in JSON format. Trying text parsing..."
    # Fallback: parse text output
    local status_txt
    status_txt="$(npx --yes supabase status 2>/dev/null)"

    local anon_key service_key api_url db_url
    anon_key="$(echo "$status_txt" | grep -i 'anon key' | awk '{print $NF}')"
    service_key="$(echo "$status_txt" | grep -i 'service_role key' | awk '{print $NF}')"
    api_url="$(echo "$status_txt" | grep -i 'API URL' | awk '{print $NF}')"
    db_url="$(echo "$status_txt" | grep -i 'DB URL' | awk '{print $NF}')"

    cat > "${REPO_ROOT}/.env.local" <<EOF
# ============================================
# LOCAL SUPABASE CREDENTIALS
# ============================================
# AUTO-GENERATED by install-supabase-wsl.sh
# DO NOT COMMIT - this file is gitignored
#
# These credentials are for LOCAL development only.
# For cloud credentials, use .env with VITE_* variables.

LOCAL_SUPABASE_URL=${api_url:-http://localhost:54321}
LOCAL_SUPABASE_ANON_KEY=${anon_key}
LOCAL_SUPABASE_SERVICE_ROLE_KEY=${service_key}
LOCAL_DB_URL=${db_url:-postgresql://postgres:postgres@localhost:54322/postgres}

# Project directory (for npx supabase commands)
LOCAL_SUPABASE_PROJECT_DIR=${PROJECT_DIR}
EOF
  else
    # Parse JSON output
    local anon_key service_key api_url db_url
    anon_key="$(jq -r '.ANON_KEY // .anon_key // empty' "$status_json")"
    service_key="$(jq -r '.SERVICE_ROLE_KEY // .service_role_key // empty' "$status_json")"
    api_url="$(jq -r '.API_URL // .api_url // "http://localhost:54321"' "$status_json")"
    db_url="$(jq -r '.DB_URL // .db_url // "postgresql://postgres:postgres@localhost:54322/postgres"' "$status_json")"

    cat > "${REPO_ROOT}/.env.local" <<EOF
# ============================================
# LOCAL SUPABASE CREDENTIALS
# ============================================
# AUTO-GENERATED by install-supabase-wsl.sh
# DO NOT COMMIT - this file is gitignored
#
# These credentials are for LOCAL development only.
# For cloud credentials, use .env with VITE_* variables.

LOCAL_SUPABASE_URL=${api_url}
LOCAL_SUPABASE_ANON_KEY=${anon_key}
LOCAL_SUPABASE_SERVICE_ROLE_KEY=${service_key}
LOCAL_DB_URL=${db_url}

# Project directory (for npx supabase commands)
LOCAL_SUPABASE_PROJECT_DIR=${PROJECT_DIR}
EOF
  fi

  rm -f "$status_json"

  log "Local credentials saved to: ${REPO_ROOT}/.env.local"
}

# ========= MAIN =========
log "Supabase Local installer for WSL Ubuntu"
log "Repository root: ${REPO_ROOT}"

if is_wsl; then
  log "Detected WSL environment."
else
  warn "WSL not detected. Script will still run on Ubuntu, but it was designed for WSL."
fi

if [ -n "${SUDO_PASS:-}" ]; then
  log "Running in unattended mode (SUDO_PASS provided)"
fi

log "Updating APT and installing base dependencies..."
do_sudo apt-get update -y
do_sudo apt-get install -y \
  ca-certificates curl gnupg lsb-release git unzip jq \
  iproute2 acl

log "Checking Docker..."
if command -v docker >/dev/null 2>&1 && docker_works; then
  log "Docker is already installed and working."
else
  log "Installing Docker Engine + Compose plugin..."
  # Remove conflicting packages (safe if not present)
  do_sudo apt-get remove -y docker docker.io docker-doc docker-compose podman-docker containerd runc >/dev/null 2>&1 || true

  do_sudo install -m 0755 -d /etc/apt/keyrings

  # Install GPG key using helper function (handles pipe issues)
  install_docker_gpg_key

  UBUNTU_CODENAME="$(. /etc/os-release && echo "${VERSION_CODENAME}")"
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu ${UBUNTU_CODENAME} stable" \
    > /tmp/docker.list.$$
  do_sudo cp /tmp/docker.list.$$ /etc/apt/sources.list.d/docker.list
  rm -f /tmp/docker.list.$$

  do_sudo apt-get update -y
  do_sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  start_docker_best_effort
  ensure_docker_access_for_current_user
fi

# Final Docker verification
if ! docker_works; then
  warn "Docker still not reachable from this shell."
  warn "On WSL, the most reliable option is Docker Desktop (Windows) with WSL integration enabled."
  warn "If you installed Docker Desktop, close this terminal and open a new WSL terminal, then re-run this script."
  die "Cannot continue without a working Docker daemon."
fi

log "Docker OK:"
docker version --format 'Client={{.Client.Version}} Server={{.Server.Version}}' 2>/dev/null || docker version

log "Checking required ports..."
check_ports_free

log "Checking Node.js (need v${NODE_MAJOR_REQUIRED}+ for Supabase CLI via npm/npx)..."
CURRENT_NODE_MAJOR="$(node_major)"
if [ "${CURRENT_NODE_MAJOR}" -ge "${NODE_MAJOR_REQUIRED}" ]; then
  log "Node.js OK (major=${CURRENT_NODE_MAJOR})."
else
  log "Installing Node.js ${NODE_MAJOR_REQUIRED}.x (NodeSource)..."
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR_REQUIRED}.x" -o /tmp/nodesource_setup.sh
  do_sudo bash /tmp/nodesource_setup.sh
  rm -f /tmp/nodesource_setup.sh
  do_sudo apt-get install -y nodejs
  log "Node installed: $(node -v) / npm: $(npm -v)"
fi

log "Using repository root as project folder: ${PROJECT_DIR}"
cd "${PROJECT_DIR}"

# Verify package.json exists (should be in repo root)
if [ ! -f package.json ]; then
  die "No package.json found in ${PROJECT_DIR}. Are you in the correct repository?"
fi

# Ensure Supabase CLI is available
if [ ! -d node_modules/supabase ]; then
  log "Installing Supabase CLI as a local dev dependency..."
  npm install --save-dev supabase
fi

log "Supabase CLI version:"
npx --yes supabase --version

# Verify supabase/ folder exists with migrations (should already exist in repo)
if [ ! -d supabase ]; then
  die "No supabase/ folder found. This script expects the repo's existing supabase/ folder with migrations."
fi

if [ ! -d supabase/migrations ] || [ -z "$(ls -A supabase/migrations 2>/dev/null)" ]; then
  warn "No migrations found in supabase/migrations/. Schema may be incomplete."
else
  MIGRATION_COUNT=$(ls -1 supabase/migrations/*.sql 2>/dev/null | wc -l)
  log "Found ${MIGRATION_COUNT} migration files in supabase/migrations/"
fi

log "Starting Supabase stack (this will pull Docker images)..."
npx --yes supabase start

log "Writing status to: ${SUPABASE_ROOT}/supabase-status.txt"
npx --yes supabase status | tee "${SUPABASE_ROOT}/supabase-status.txt"

# Generate .env.local with captured credentials
generate_env_local

# ========= START OPS SERVER UNDER PM2 =========
start_ops_server_pm2() {
  log "Setting up ops-server under PM2..."

  # Install PM2 globally if not present
  if ! command -v pm2 >/dev/null 2>&1; then
    log "Installing PM2 globally..."
    npm install -g pm2
  fi

  # Stop existing zulu-ops-server if running
  pm2 delete zulu-ops-server 2>/dev/null || true

  # Create .env.ops from sample if it doesn't exist
  if [ ! -f "${REPO_ROOT}/.env.ops" ] && [ -f "${REPO_ROOT}/.env.ops.sample" ]; then
    log "Creating .env.ops from sample..."
    cp "${REPO_ROOT}/.env.ops.sample" "${REPO_ROOT}/.env.ops"
    warn "Please edit .env.ops with your SUPABASE_SERVICE_ROLE_KEY"
  fi

  # Start ops-server under PM2
  log "Starting ops-server as PM2 daemon (zulu-ops-server)..."
  pm2 start "${REPO_ROOT}/deployment/ops-server.mjs" \
    --name zulu-ops-server \
    --cwd "${REPO_ROOT}" \
    --time

  # Save PM2 process list
  pm2 save

  # Configure PM2 startup (optional, for persistence across reboots)
  log "Configuring PM2 startup for persistence..."
  pm2 startup systemd -u "$USER" --hp "$HOME" 2>/dev/null || true

  log "Ops-server is now running under PM2"
  pm2 list
}

start_ops_server_pm2

cat <<OUT

============================================================
Supabase Local + Ops Server Running
------------------------------------------------------------
Supabase Studio:  http://localhost:54323
API URL:          http://localhost:54321
DB Port:          54322
Ops Server:       http://localhost:8731

Project folder:   ${PROJECT_DIR}
Status saved:     ${SUPABASE_ROOT}/supabase-status.txt
Credentials:      ${REPO_ROOT}/.env.local

Ops Server (PM2):
  pm2 list                    # View status
  pm2 logs zulu-ops-server    # View logs
  pm2 restart zulu-ops-server # Restart
  pm2 stop zulu-ops-server    # Stop

NEXT STEPS:
  1. Edit .env.ops with your SUPABASE_SERVICE_ROLE_KEY (if not set)

  2. Apply migrations to create schema:
     ./deployment/apply-migrations.sh
     (This applies all ${MIGRATION_COUNT:-364} migrations)

  3. Sync data from cloud (via UI or CLI):
     Open http://localhost:8731 or run:
     SUPABASE_SERVICE_ROLE_KEY=<key> ./deployment/clone-supabase-data.sh

Useful commands:
  cd ${PROJECT_DIR}
  npx supabase status
  npx supabase stop
  npx supabase start
  npx supabase db reset --linked=false  (re-apply all migrations)

If you ever get "permission denied" for Docker:
  - close this WSL terminal
  - open a new one
============================================================

OUT
